apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-media-pvc
  namespace: mindledger
  labels:
    app.kubernetes.io/name: mindledger
    app.kubernetes.io/component: api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-logs-pvc
  namespace: mindledger
  labels:
    app.kubernetes.io/name: mindledger
    app.kubernetes.io/component: api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-static-pvc
  namespace: mindledger
  labels:
    app.kubernetes.io/name: mindledger
    app.kubernetes.io/component: api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: standard
